---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
  labels:
    app.kubernetes.io/managed-by: manual
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app.kubernetes.io/managed-by: manual
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    app.kubernetes.io/managed-by: manual
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
